### ISSUE TITLE
Bring back the browserify compiled file

### ISSUE THREAD

**Issue by xiclopex** [matfish2/vue-tables-2#103]
- Vue.js version: 2.1.10
- consumed using: browserify (Version Tree: ebbd40f1b0 )
- FULL error message (including stack trace): I want to upgrade the package version but I don´t know how to generate the browserify compiled version (I am using as a browser package direct in my app)

**Comment by matfish2** [comment]
I don't understand. You say you are using `browserify`. Why can't you compile the package?

**Comment by xiclopex** [comment]
I dont know how to generate vue-tables.min.js 
I used vue-tables.min.js  in my web app globally, in the new version of the amazing vue-tables-2 this file does not exist and I can't build a similar pack.
Sorry for my english.

**Comment by matfish2** [comment]
You don't need to generate it if you are using browserify (or any other module bunder). Simply require it as documented and run the bundler.

I am not thrilled to create a single precompiled file because I am using an event bus, which is nothing more than a fresh instance of Vue. That means you will have Vue loaded twice - once by the your own app and once by the package. This is not an issue when you require the package as documented, because the bundler is smart enough to use caching.
