### ISSUE TITLE
set option orderBy.ascending invalid

### ISSUE THREAD

**Issue by xushaocong** [matfish2/vue-tables-2#155]
when i use serverTable, i set the option
```
options: {
  orderBy: {
     ascending: false
  }
}
```
Whether I set it to `true` or `false`, the request params always be `ascending: 1`

**Comment by vesper8** [comment]
I can verify the same problem!!

I also noticed this only happens when I use the Vuex version

```
Vue.use(ServerTable, null, true);
```

?query=&limit=20&orderBy=id&ascending=1&page=1&byColumn=0
ascending=1 always regardless if I set ascending: true or ascending: false in the options

however if I do
```
Vue.use(ServerTable);
```

Then ascending=0 or =1 depending on the tableOptions

all other parameters are passed correctly

```
tableOptions() {
        const options = {
          orderBy: {
            column: 'id',
            ascending: false,
          },
          pagination: {
            chunk: 10,
            dropdown: false,
          },
          perPage: 10,
          perPageValues: [10, 50, 100],
        };
        return options;
      },
```
