### ISSUE TITLE
Pagination request on click, table styling

### ISSUE THREAD

**Issue by dobromir-bogatev** [matfish2/vue-tables-2#163]
- Vue.js version: 2.3.2
- consumed using: (webpack)

Is there a way to make the pagination make requests on next page click? I want to make it so it sends requests in small chunks rather than requesting a huge piece of data for the table. 

Another question I want to ask is if there is a way to make like a template for my table which uses different CSS (not bootstrap). I want to use your functionality, but my styles.

**Comment by matfish2** [comment]
A. i don't understand. If you wrote the server-side code correctly, then the page parameter coupled with the per page limit allows you to limit the response to the maximum values per page.

B. If you are not using bootstrap at all, you can write your own styles to match with the bootstrap classes. Otherwise you can override the style within the scope of your table (this is easily done with a precompiler like SASS that lets you use nesting)
