### ISSUE TITLE
How to use Custom Filters with multiple tables on same page?

### ISSUE THREAD

**Issue by pushamaku** [matfish2/vue-tables-2#183]
- Vue.js version: 2.26
- consumed using: webpack
- FULL error message (including stack trace): N/A
- relevant code: below
- steps for reproducing the issue: N/A

I have 2 tables vue-tables-2 components on the same page, everything works fine, including searching within each, as I use refs, e.g.,

```
this.$refs.table1.setFilter(query);
this.$refs.table2.setFilter(query);
```

Now I also have custom filters setup, basically duplicated in both components, e.g.,

```
customFilters: [
          {
            name :'device',
            callback: function(row, filters) {
              return filters.indexOf(row.device_type) >= 0
            }
          },
          {
            name :'building',
            callback: function(row, filters) {
              return filters.indexOf(row.building_name) >= 0
            }
          },
]
```

When I trigger these custom filters from some methods (duplicated in each component) by using the Event bus, it filters items only in the other table, and not in itself.

```
toggleBuildingFilter( buildings ) {
      this.buildingSelected = buildings
      Event.$emit('vue-tables.filter::building', buildings)
    },
    toggleDeviceFilter( devices ) {
      this.devicesSelected = devices
      Event.$emit('vue-tables.filter::device', devices)
    },
```
I tried to rename the filters in one of the tables, and while the other table did not get affected, it did not filter itself at all.

Can you please advise on how one would be able to trigger custom filters on a per table basis?

Thank you

**Comment by matfish2** [comment]
After testing it myself, the problem seems to be that when you declare two identically named custom filters in different tables, the events registrar overrides the first registered event with the second, as they have the same name (see `register-client-events.js`). So this is to be expected.

You say you changed the filter names in one of the tables and still had a problem. I tried it and was not able to reproduce the problem.

Please check:

A. that non of your custom filters' names collide with the normal filters' names (i.e the columns keys).
B. That you are emitting the correct event name, i.e that it corresponds exactly to the `name` key in `customFilters` for each table.

At any case, since the table now has an optional `name` prop, I think I will use it to create "namespaced" events, such as `vue-tables.my-table.filter::building`, thus allowing identical custom filters between tables.

**Comment by pushamaku** [comment]
@matfish2,

Thank you very much for pointing me in the right direction. After I debugged a bit with Vue devtools, I was able to find the bug and it is working now with the renamed filters.

Yes, the namespaced events would be helpful in a future release.

Thank you again for your time and efforts with this! Much appreciated!
