### ISSUE TITLE
sort and filter  formatted columns

### ISSUE THREAD

**Issue by phamvanthanh** [matfish2/vue-tables-2#202]
Hi @matfish2,
How to filter and sort in component rendered columns? Eg: I formatteed cell values to be hyperlink.

**Comment by phamvanthanh** [comment]
I work around with it this way:
1. Adding a column with origin data ( not formatted) so built in filter can do
2. Hide that column with columnDisplay options ( it is not actually completely hidden)
=> finish filter
3. Add a customFilter on the formatted column but using origin field data.
=>finish sorting
I am not sure it is good or not but there should be a better way :(

**Comment by matfish2** [comment]
If the custom column is an *existing* one, to which you add a template as an additional layer, then both sorting and filtering work in reference to the *original* data in that column.

As for *new* custom columns, it is more tricky, because the column is not actually a part of the dataset, and is being added as a *derived* column on render time.  

So, whenever sorting or filtering of a custom column is necessary, the first option is the way to go. 
E.g in case of a hyperlink I would create a column (say `link`) containing the content (text) of the `a` tag, which is probably what you want to sort and filter. Then I would pass an additional `url` property to each row, which won't declared in the `columns` prop. The template would look something like this:

```html
 <template slot="link" scope="props">
        <div>
            <a class="fa fa-edit" :href="props.row.url">{{props.row.link}}</a>
        </div>
      </template>
```

Of course if you have more data that needs to be attached you can add some sort of `data` object to each row, and get the data from there.

**Comment by MatiasManevi** [comment]
I'll appreciate help with this.

> If the custom column is an _existing_ one, to which you add a template as an additional layer, then both sorting and filtering work in reference to the _original_ data in that column.

What do you mean by existing column/new column? I do not  quite understand what are you referring.

I am having problems to FILTER rows using colums which render a template.

For example I have a boolean field  `perceive_interest` and depending on the value I want to render `Yes` or `No`. 

The custom template for that column field is something like this:

````
perceive_interest: (h, row, index) => {
      return row.perceive_interest ? 'Yes' : 'No';
}
````

But sadly I am not able at all to filter rows by using this column filter with the texts `Yes` nad `No`.

(Sorting works).

**Comment by matfish2** [comment]
https://matanya.gitbook.io/vue-tables-2/client-table/filtering-algorithm

```js
filterAlgorithm: {
  percieve_interest(row, query) {
    return (query.toLowerCase==='yes' && row.perceive_interest) ||  ((query.toLowerCase==='no' && !row.perceive_interest) ;
  }
}
```

**Comment by MatiasManevi** [comment]
> [](https://matanya.gitbook.io/vue-tables-2/client-table/filtering-algorithm)
> 
> ```js
> filterAlgorithm: {
> ```

It works like a charm!

Thanks a lot for the quick support!
