### ISSUE TITLE
Pagination open in new tab on Firefox

### ISSUE THREAD

**Issue by ymoreiratiti** [matfish2/vue-tables-2#203]
Versions:
* vue: 2.3.4
* vue-tables-2: 0.5.0
* webpack: 2.2.1
* Firefox 54

When i change the pagination on VueTables2 using firefox, the component change the page and open a new popup in blank.
I used the inspector and see the line:

```
<li class="VuePagination__pagination-item page-item ">
     <a href="javascript:void(0);" class="page-link">2</a>
</li>
```

I removed the `href="javascript:void(0);" ` and this seem to fix it.

Any ideas? Anybody is having the same problem?

**Comment by matfish2** [comment]
I don't know why FF opens a new tab.
While removing the href altogether is considered a [best practice](https://stackoverflow.com/questions/134845/which-href-value-should-i-use-for-javascript-links-or-javascriptvoid0. ) nowadays (Third answer), the problem is that the pointer cursor depends on it, and I am reluctant to compel the user to include additional css, other than the bootstrap framework.
I am open to suggestions as to how to handle it.

**Comment by CoolGoose** [comment]
@matfish2 maybe something like
```css
<span role="button class="page-link">2</a>
```
Looks the same and covers cursor pointer.

**Comment by matfish2** [comment]
Updated pagination plugin as per @CoolGoose's suggestion
