### ISSUE TITLE
Question:How do I query hidden columns?

### ISSUE THREAD

**Issue by jeanaio** [matfish2/vue-tables-2#213]
How do I query hidden columns?
E.g
Https://datatables.net/examples/basic_init/hidden_columns.html

**Comment by matfish2** [comment]
I assume that:
A.When you say "hidden columns" you mean properties of the dataset that were not declared as columns, or columns that were hidden using the `columnsDisplay` option. 
B. when you say "query" you mean the using the general filter (one filter for all columns).

As it stands now the search only iterates through properties that were declared in the `columns` prop. So, columns that were hidden due to changing the window size are searchable, whereas columns that were not declared at all are not.
