### ISSUE TITLE
Provide better way to access open child rows

### ISSUE THREAD

**Issue by vpillinger** [matfish2/vue-tables-2#271]
In order to figure out the open child rows (in my case, I needed to force a refresh of the child row) I had to write this method:
`
           refreshOpenChildRows() {
                for (const open_row in this.$refs.table.rowsToggleState){
                    if(this.$refs.table.rowsToggleState.hasOwnProperty(open_row)){
                        const row_id = open_row.split('_')[1];
                        // do some stuff with row_id
                    }
                }
            }
`

There should be an easier way to get the currently open child rows. It should also allow the programmer to get the Component instance so that they can call methods on it (tell it to refresh, pass it new data, ect).

My use case is that I have nested tables, so if an item moves from sub table A to sub table B, I need to refresh the data on both sub tables to keep them in-sync with each other.

**Comment by matfish2** [comment]
This only applies to a case where the child row is declared as a separate component (ie. not using scoped slots or a function, in which case there is no component to retrieve).
I suppose I can check if the consumer used a component for the child row, and in that case allow him to get those components.
So the API may look something like that:

```js
this.$refs.table.getOpenChildRowsComponents(row = null) {
}
```

Then, in case of the user passes no argument all open child row components are retrieved.
Otherwise, if the user passes an array of ids, only those ids will be retrieved (by checking the 'id' on the component).

In case the child row was not declared as a component an error will be thrown.

**Comment by vpillinger** [comment]
Since you imply that it is possible to use a scoped slot with a child row, can you please provide directions on how to do that? I wanted to use a scoped slot initially, but did not read that option in the documentation. Is there a specific slot ("child-row"?) that needs to be used?

**Comment by matfish2** [comment]
Actually, I thought I already implemented a scoped slot for a child row. 
I've added a `child_row` scoped slot. Please see the docs.
