### ISSUE TITLE
Adding custom checkbox filters after global search

### ISSUE THREAD

**Issue by sergiocastrovale** [matfish2/vue-tables-2#395]
First of all, thanks for the excellent package. 

I'm trying to add a custom filter that iterates through all of my `permissions`, adds a checkbox filter for each of them, and toggling each checkbox will narrow/expand the list of results and I'm a bit lost on how to do so. I've attached an example of what I mean below.

What I don't get is:

1) How can I render such a filter? I assume it would be with `afterFilter` but I don't understand how to do it.
2) How would I iterate through `mylist.permissions` and make it so clicking on them would trigger a change on my list?

Thanks!
![mockup](https://user-images.githubusercontent.com/8822036/35018345-f41192ba-fb18-11e7-9c19-8d3b0d28263e.png)

**Comment by matfish2** [comment]
1. Depending on your design you can either add it externally or indeed as an `afterFilter` [slot](https://vuejs.org/v2/guide/components.html#Named-Slots). 
2. Use a [custom filter](https://github.com/matfish2/vue-tables-2#custom-filters). Emit an event when you permissions list changes and send through the current value to filter by. If you are using the server component a request will be sent with the selected permissions. Otherwise, you need to provide a callback function to decide which row pass the filter.
