### ISSUE TITLE
adding the template slot for heading breaks down the column filter value

### ISSUE THREAD

**Issue by DeepakAryal** [matfish2/vue-tables-2#405]
I need to use the template slot for heading to and i did so. but also i have used filterable fro that column. but now the placeholder is breaks down. Now it shows `Filter by [Object object]` instead of `Filter by {column}`

**Comment by matfish2** [comment]
By default the search placeholder is using the heading as a variable. When the heading is an object it is stringified to [Object Object], since the plugin doesn't know what the string version of the heading should be. I suppose I could use the uppercase version of the column name, but that wouldn't account for localization. In the mean time you can change the placeholder text so that it won't contain the `{column}` variable.

**Comment by DeepakAryal** [comment]
Then, i can not display placeholders for my filters dynamically according to column heading or name?

This means if we add the slot for heading, the `{column}` variable is no more validate.

I have column named `id` and i want my search placeholder for that column looks like `filter by Id`. is it possible?

**Comment by matfish2** [comment]
Not currently

**Comment by DeepakAryal** [comment]
ok thanks

**Comment by boriskogan81** [comment]
How can we set filter placeholders manually without redoing the entire filtering functionality?
