### ISSUE TITLE
Using a computed property as a column?

### ISSUE THREAD

**Issue by DaveKP** [matfish2/vue-tables-2#431]
I can't find any reference to this - is it possible? I'm using typescript and have a class:

```
Class Order{
     id:string;
     ref:string;
     .
     .
     .
     status:int;
     get displayStatus():string{
         return this.status.DoSomeStuff();
    }
}
```

I'd like to be able to display and filter the displayStatus(), because the status itself isn't exactly descriptive in the UI. I think I had it working in a previous build when I was just using interfaces, but feel like I'm missing something now.

Sorry, this is more of a query than an issue but figured this is the best place to ask - perhaps I'm just approaching it wrong?

**Comment by matfish2** [comment]
I see two options:

1. Instead of passing the original dataset to the `:data` prop, use a computed property that maps through the data and performs the necessary modifications.
2. Using the `templates` option, you can modify the presentation of the column (probably should rename `templates` to `presenters` which is more accurate and descriptive).

**Comment by DaveKP** [comment]
Cheers - I'm leaning towards 1, seems like it will make the filtering easier.
