### ISSUE TITLE
fixing Invalid prop: errors

### ISSUE THREAD

**Issue by Vad1mo** [matfish2/vue-tables-2#542]
- Vue.js version: 2.5.2
- consumed using: (webpack)

I get the following error message, while using vuetable-2, I try to find out where I have an error, but it is not clear to me. 

Could someone point me where the error might be?  

```
[Vue warn]: Invalid prop: type check failed for prop "data". Expected Array, got Null.

 Error in render: "TypeError: Cannot read property 'filter' of null"

```

![image](https://user-images.githubusercontent.com/1492007/41167105-44d75592-6b42-11e8-8e56-ca1b00708431.png)

**Comment by rSammy** [comment]
Hello.
I wonder why this is not specified in the docs.

I guess you're using serverside

You must return an object.

{
    data : [{someObject},{someObject},{someObject}],
    count : someNumberOfTotalResults
}

**Comment by Vad1mo** [comment]
I am actually using client side. However I have a few holes in my cells (cell value is nul) not sure if that's the reason. Other tables are working fine.

**Comment by rSammy** [comment]
Are you using your data this way https://github.com/matfish2/vue-tables-2#client-side ?

**Comment by rSammy** [comment]
Do you use vue-devtools ?
Can you see events being triggered ?

**Comment by matfish2** [comment]
The error message is pretty clear. The `data` prop expects an array, and you are passing it `null`. 
If you are using an async function to get the data make sure not to instatiate the component until the data is assigned, using a v-if loaded flag. (As mentioned in the docs). Otherwise you can make your initial `data` property an empty array.
