### ISSUE TITLE
Page parameter in the Ajax request gets stuck when using preserveState option

### ISSUE THREAD

**Issue by vstruhar** [matfish2/vue-tables-2#543]
First I want to thank you for developing this amazing Vue component. While using it I have found one small bug.

- Vue.js version: 2.5.16
- consumed using: webpack (vue-cli 3.0.0-beta.15)
- FULL error message (including stack trace): no error
- relevant code:
`preserveState: true` is set in the options
- steps for reproducing the issue: 
1. Open page where the table is used with pagination
2. Click on second page in the pagination
3. Navigate away to some other page
4. Then go back to the previous page where the second page was opened
5. Now try to click on some other page number in the pagination
6. The result is that in the ajax request the `page` parameter is stuck at 2 (the value that was preserved when navigated away)

![2018-06-11 20_06_45](https://user-images.githubusercontent.com/6599021/41249024-1c0104ce-6db3-11e8-9038-295d85ce409a.gif)

**Comment by matfish2** [comment]
After some tinkering with vue-router, I have discovered that while the component **is** destroyed when moving to another page, it is referenced once again when navigating back. So vue-dev-tools will show you the state of the **new** component, while under the hood the `this` keyword will refer to the **old** instance, which explains why it keeps refering to the preserved page on the allegedly destroyed component.
I am still to figure out if this is expected behaviour and how it can be tackled. You are welcome to chip in :)
