### ISSUE TITLE
User material icon for sort icon in vue-table-2

### ISSUE THREAD

**Issue by wiadev** [matfish2/vue-tables-2#562]
Hi
I wanna use a material icon for sort icon but can't find a way to do it.
e.g I wanna use the following icon.
`<i class="material-icons">arrow_downward</i>`

Thanks

**Comment by francislavoie** [comment]
This is what you're looking for: https://github.com/matfish2/vue-tables-2#virtual-dom-functions

Use template functions for each column to do custom rendering. It's easier with JSX, install the babel plugin for vue: `transform-vue-jsx`

**Comment by rSammy** [comment]
Hi,

You can do so just by using slots

**Comment by jfhuete** [comment]
What is the slot that I have to use to do it?, In the documentation I can't find an slot that insert the html in the headers columns

**Comment by jace-carter** [comment]
For anyone getting here in the future:

It's not documented super well - but you can customize these with the sortIcon options for the table.

For example I wanted to use font-awesome since that's the icon lib I'm using and this was how I did it:
`  
sortIcon: {
  is: 'fa-sort',
  base: 'fa',
  up: 'fa-sort-up',
  down: 'fa-sort-down',
},
`
