### ISSUE TITLE
server table not filtering and pagination not working

### ISSUE THREAD

**Issue by Tchayo** [matfish2/vue-tables-2#619]
After setting up vue-table-2 server it displays data as expected but filter and pagination do not work..all the data is displayed on a sing page even if you select the second page in pagination icon. 
The client table works perfectly.

**Comment by ptsimard** [comment]
Having the same problem here. Data gets loaded but all displayed in single page, no filtering/pagination.

**Comment by thieums** [comment]
We're using vue-table-2 server in production and it's working perfectly.
You probably should debug on API side and check what you return to your http client.

**Comment by Tchayo** [comment]
the data works just fine with the client table so that is not the issue. Maybe some extra settings are required, I'm not certain. Show us how you made the server table work.

**Comment by AuditeMarlow** [comment]
Having the same issue. The Server Table component _does_ update its `query` data prop, but is never added as a value to the `query` parameter in the URL.

**Comment by thieums** [comment]
You don't have to expect pagination and filtering working on client side when using server mode.
In server mode you should handle pagination and filters on server (API) side.

**Comment by AuditeMarlow** [comment]
It seems I misinterpret what this issue is about, my described issue differs from the initial post. It does indeed seem like there is no filtering or pagination setup on the API. This is all manual labor unfortunately, but as expected. The [documentation](https://github.com/matfish2/vue-tables-2#server-side) describes how you should go on about server side filters and has a [Laravel example](https://raw.githubusercontent.com/matfish2/vue-tables-2/master/server/PHP/EloquentVueTables.php) available.

**Comment by Tchayo** [comment]
@thieums switched to the client mode. Everything works nicely. Still not conversant with the serve side configurations. If there are any materials out there for that, point me to them.
