### ISSUE TITLE
Export csv, xls or pdf

### ISSUE THREAD

**Issue by AcevedoCarles** [matfish2/vue-tables-2#646]
- Vue.js version: 2
- consumed using: (browserify/webpack/rollup): webpack

Hello, I want to export vue-tables in csv, xls or pdf. Can anybody help me?

Thanks

**Comment by gitBC** [comment]
Agreed, I have an export button for my reports, but since my data uses server tables and is generally **paginated** to the front end, I instead send a request to my back end to compile a file for the user to download. I pass off a request to the backend which includes the sort order and any query filters that I've set on my server tables. Then, I generate a SQL query to match retrieved data in the report and generate an excel file via PHPSpreadsheet or XLSXWriter. This functionality is, however, completely separate from vue-tables-2 and requires its own implementation

**Comment by TheStoof** [comment]
Agreed. All you need to do is add a button that can get the data from VueTables (if you want) and export it using something like:

https://github.com/clarketm/TableExport/tree/v5.2.0

**Comment by AcevedoCarles** [comment]
Oh great!!  Thank you very much

**Comment by jeremykenedy** [comment]
I found a great way to handle this using https://github.com/jecovier/vue-json-excel 
I did attempt to use the library referenced by @TheStoof 

Here is how I handled exporting the data:

1. `npm install vue-json-excel`
2. Add the import: `import JsonExcel from 'vue-json-excel';`
3. Add the component: 
```
export default {
  components: {
    downloadExcel: JsonExcel,
  },
...
```
4. Add the data plug for what type for the radio selection:
```
  data() {
    return {

      ...
      
      dataExportType: 'csv',
    };
  },
```
5. Add a method to get the vue-tables-2 data:
```
  methods: {

    ...
    
    exportInventoryReportData() {
      return this.$refs.intentoryReprtingTable.filteredData;
    },
  },
```
6. Add the HTML and component call to the mockup:
```
<div class="radio form-check-inline ml-1">
  <input
    id="exportRadioCsv"
    v-model="dataExportType"
    type="radio"
    value="csv"
    checked
  >
  <label for="exportRadioCsv">
    CSV
  </label>
</div>

<div class="radio form-check-inline">
  <input
    id="exportRadioXls"
    v-model="dataExportType"
    type="radio"
    value="xls"
  >
  <label for="exportRadioXls">
    XLS
  </label>
</div>

<download-excel
  class="btn btn-primary"
  :fetch="exportInventoryReportData"
  :type="dataExportType"
  :name="'report.'+dataExportType"
>
  Download Data
</download-excel>
```
