### ISSUE TITLE
The setFilter method throws error when the search input is in another component

### ISSUE THREAD

**Issue by junedchhipa** [matfish2/vue-tables-2#707]
- Vue.js version: 2.6.10

**Error Message:**
[Vue warn]: Error in callback for watcher "queryFilter": "TypeError: Cannot set property 'value' of null"

The line which causes the problem is
`this.$el.querySelector('.VueTables__search input').value = query;`

If I put the `<table>` in one component, and the filter `<input>` in the parent component, the callback throws an error trying to set the `<input>`'s value.
As input will not be accessible in `this.$el`

**Comment by matfish2** [comment]
I'm not sure I understand the scenario of "If I put the <table> in one component, and the filter <input> in the parent component", Are you using your own custom template?

**Comment by ionutraducanu** [comment]
Hello @matfish2 , I have the same issue after a recent update to latest version.

I have filterable as an empty array and still, it crashes.
vue.common.dev.js:1893 TypeError: Cannot set property 'value' of null
    at VueComponent.module.exports (set-filters-dom.js:36) 
because the element doesn't exists
this.$el.querySelector('.VueTables__search__input').value = query;
