### ISSUE TITLE
Why use a date-range picker that requires jQuery in vue?

### ISSUE THREAD

**Issue by jeffster9** [matfish2/vue-tables-2#727]
First of all, props to you for developing this very flexible component. I truly hope to use it in my current work (I'm still testing usability (ServerTable)). You've done great work here! That being said...

This is not necessarily a bug (issue) report but an issue I have w/ the fact that the date-range picker you've chosen to support requires jQuery to be available globally. One of the main goals in development is include as little code as possible. We are already using Vue.js here - a fully dynamic/responsive framework. There are many options available for date-range pickers that rely on Vue alone and do not require jQuery; so, why choose to support one that requires it globally? How would one go about using an alternate date-range component, opposed to the currently supported daterangepicker, with ServerTable?

**Comment by matfish2** [comment]
While I can see your point the date picker is optional. You can use your own custom filter and place it in the th of the native filter (see docs). The reason I picked it is because it's a battle tested widely used one. If you have a better idea for a picker that has fewer dependencies (maybe Pikaday? Although I'm not sure they offer range picking out of the box), I will be happy to consider it as the default (Might be good to offer multiple picker options). You are of course welcome to send a PR if you are so inclined. Closing for now.
