### ISSUE TITLE
[Feature Request] Add TailwindCSS Theme

### ISSUE THREAD

**Issue by vesper8** [matfish2/vue-tables-2#744]
TailwindCSS is taking the dev world by storm and is considered by many as the new best thing since sliced bread =D

There are currently no good vue table components in my opinion, there is one but it's nowhere near as rich as this package. Would be great if someone could create a new theme compatible with TailwindCSS so we can use this awesome package without having to pull in Bootstrap 3/4 or Bulma

**Comment by matfish2** [comment]
Related to #738. I think a more overarching solution is required here. I.e decouple functionality from UI as much as possible, E,g: (https://adamwathan.me/renderless-components-in-vuejs/). Once this is achieved I think I'll deprecate the admittedly cumbersome templates and themes in favour of this new approach. Ideally one would be able to use the modular approach to a. position existing components b. using scoped slots, build his own UI for the component itself. This will all be wrapped in a consumer-created component, which is the one he'll reference, instead of the core v-{x}-table component

**Comment by matfish2** [comment]
Added tailwind theme for subscribers (private repo)
