### ISSUE TITLE
Is there a way to pass additional props to cell template components?

### ISSUE THREAD

**Issue by zmkpr0** [matfish2/vue-tables-2#95]
Is there a way to pass additional props to cell template components? I know I can set the value I want to pass on every row, but I'm looking for something more elegant.

**Comment by matfish2** [comment]
Well, if the value is unique to each row then passing it to each row sounds like the way to go. Otherwise, the template component is merely a wrapper, which gives you access to your row data. It is not meant to have any other props of itself. Inside your template you can use other components and even pull data from up the tree (If you are using a shared state, like Vuex, this should be a no brainer).

**Comment by zmkpr0** [comment]
The value is not unique to each row. It may be unique for each table or each column. 

My usecase is I want to apply some formatting to the value. There's an input param that specifies the output format. Let's say I want to format to cells in the same table with different format. The only way I can see now is to create one component for each format. What I want to do is to reuse the same component, and just pass the pattern as a prop. Is there a way to do that?
